### PR TITLE
Support for Visual Studio 2019

### PR DESCRIPTION
**Pull request by EdenRidgway**
I've updated the vsix manifest to support 2019 and it seems to work (tested using VS.Net 2019 Community Edition).

### CODE REVIEW

**Comment by AvgustPol** [comment]
YAY

yay

I'm waiting for it so much !

**Comment by realvizu** [comment]
Thanks for the contribution!
But unfortunately it does not make it possible to release a VS2019 version because your patch applies to the master branch which contains a bunch of work-in-progress enhancements that won't be stable (release quality) for the next several months.

In order to create a release-ready VS2019 version the last stable version (https://github.com/realvizu/QuickDiagram/commit/8220c80a6423d59d0ec32f38a1a4dd9d3d68653e) must be patched, as described here in this conversation: https://github.com/realvizu/QuickDiagram/issues/17#issuecomment-508906110

I've created a new branch called **vs2019** (https://github.com/realvizu/QuickDiagram/tree/vs2019) from that last stable version just to see how hard would it be to add VS2019 support. It didn't even build with current version of VS2017 so I had to update the VSSDK. And the new VSSDK added some analyzers that now report a bunch of threading problems and of course a message to update to AsyncPackage. So there's some more work to do before I can release a VS2019 version.

**Comment by realvizu** [comment]
VS2019 version released, see https://github.com/realvizu/QuickDiagram/issues/17#issuecomment-578128070

**Comment by AvgustPol** [comment]
@realvizu  thanks for VS2019 support ! C:

**Pull request closed without merging**
